export { Projects } from './[categoryId]'
export { ProjectsDetails } from './[categoryId]/[projectId]/ProjectsDetails'
export { QuestDetails } from './[categoryId]/[projectId]/Quests/[questId]/QuestDetails'
export { SubmitSolution } from './[categoryId]/[projectId]/Quests/[questId]/SubmitSolution'
export { Solution } from './[categoryId]/[projectId]/Quests/[questId]/Solution/[solutionId]/Solution'
