spring:
  datasource:
    url: jdbc:postgresql://ec2-13-125-211-219.ap-northeast-2.compute.amazonaws.com:5432/fornerds
    username: admin
    password: fornerds#1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        packagesToScan: com.fornerds.domain


  output:
    ansi:
      enabled: always

server:
  port: 8080

logging:
  level:
    root: INFO
    com.fornerds: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

jwt:
  secret: sfja9fWDSXy8sPThPmfbQSZVmTTgBxm4
  expiration: 86400000 # 1 day in milliseconds